# 用sklearn工具快速的实现多标签文本分类打下baseline

## 一个用KNN做iris的快速入门例子

In [55]:
'''准备工作'''
# 引入数据集，sklearn包含众多数据集
import sklearn
from sklearn import datasets
# 将数据分为测试集和训练集
from sklearn.model_selection import train_test_split
# 利用邻近点方式训练数据
from sklearn.neighbors import KNeighborsClassifier
# 引入数据,本次导入鸢尾花数据，iris数据包含4个特征变量
iris = datasets.load_iris()

In [63]:
dir(sklearn)

In [22]:
print(type(iris))
for thing in iris:
    print(thing)

<class 'sklearn.utils.Bunch'>
data
target
frame
target_names
DESCR
feature_names
filename


In [31]:
print(iris.filename)
print(iris.feature_names)
print(iris.target_names)

D:\Anaconda\envs\Deep\lib\site-packages\sklearn\datasets\data\iris.csv
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa' 'versicolor' 'virginica']


In [24]:
# dir(datasets)
# help(datasets.load_iris)
'''查看函数说明的两大法宝: dir help'''

'查看函数说明的两大法宝: dir help'

In [37]:
# 特征变量
iris_X = iris.data
print(type(iris_X))
print('特征变量的长度',len(iris_X))
print('每一行的长度',len(iris_X[0]))
print(iris.feature_names)
print(iris_X[0])

<class 'numpy.ndarray'>
特征变量的长度 150
每一行的长度 4
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
[5.1 3.5 1.4 0.2]


In [39]:
# 目标值
iris_y = iris.target
print(type(iris_y))
print('鸢尾花的目标值',len(iris_y))
print(iris.target_names)
print(iris_y)

<class 'numpy.ndarray'>
鸢尾花的目标值 150
['setosa' 'versicolor' 'virginica']
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [46]:
# 利用train_test_split进行训练集和测试机进行分开，test_size占30%
X_train,X_test,y_train,y_test=train_test_split(iris_X,iris_y,test_size=0.3)
# 我们看到训练数据的特征值分为3类
print(y_train)
# print(X_test)

[2 0 1 1 0 1 1 2 1 2 0 0 1 2 0 0 1 0 1 2 0 2 1 1 0 2 1 0 1 2 1 0 1 2 1 1 2
 2 1 0 0 2 2 0 0 1 0 1 1 0 1 1 1 1 0 2 1 0 1 1 1 0 2 2 1 2 0 2 0 2 0 0 2 0
 2 2 1 1 0 2 0 2 2 2 1 1 2 1 2 1 1 2 0 1 0 1 2 0 1 2 1 0 0 2 2]


In [50]:
# 一步就train好
knn = KNeighborsClassifier()
# 进行填充测试数据进行训练
knn.fit(X_train,y_train)

params = knn.get_params()
print(params)

{'algorithm': 'auto', 'leaf_size': 30, 'metric': 'minkowski', 'metric_params': None, 'n_jobs': None, 'n_neighbors': 5, 'p': 2, 'weights': 'uniform'}


In [51]:
score = knn.score(X_test,y_test)
print("预测得分为：%s"%score)

预测得分为：0.9555555555555556


In [53]:
# 预测数据，预测特征值
print(knn.predict(X_test))
# 打印真实特征值
print(y_test)

[1 0 2 2 0 1 2 2 0 2 2 0 2 2 2 1 1 0 0 2 0 1 0 1 0 1 0 0 0 0 1 0 2 2 0 1 1
 2 0 1 2 2 1 0 0]
[1 0 2 2 0 2 2 2 0 2 2 0 2 2 2 1 1 0 0 2 0 1 0 1 0 1 0 0 0 0 1 0 2 2 0 2 1
 2 0 1 2 2 1 0 0]


That's all, over. Faking easy man

## 文本例子

使用二分类情感分析的数据集做，理论上来说，将对应的文本和标签转换成两个ndarray就可以，可以使用自己创建vocab和tokenize的方式，也可以使用torch_bert的tokenizer

## 数据预处理

In [53]:
import numpy as np
import fanTools
import sklearn
from sklearn import datasets
from sklearn.model_selection import train_test_split

In [179]:
# # 第一步: Tokenize
# sen = "我今天中午去餐车吃了鸡肉饭和一瓶饮料"
# def sentence_get_BERT_Token(samples):
#     '''利用online的库做tokenize，适合小数据'''
#     import torch
#     from pytorch_transformers import BertTokenizer
#     model_name = 'bert-base-chinese'
#     tokenizer = BertTokenizer.from_pretrained(model_name)
#     tokenized_text = [tokenizer.tokenize(i) for i in samples]
#     input_ids = [tokenizer.convert_tokens_to_ids(i) for i in tokenized_text]
#     res = []
#     for i in input_ids:
#         res.extend(i)
#     return res
# res = sentence_get_BERT_Token(sen)
# res
# # g = np.array(res,dtype=int)
# # g

In [3]:
# 文本分类数据集路径
posdata_path = '../re_datasets/clothing_comment_情感分析/posdata.txt'
negdata_path = '../re_datasets/clothing_comment_情感分析/negdata.txt'

In [4]:
# 读入数据集
pos_list = fanTools.read_file_to_list(posdata_path)
neg_list = fanTools.read_file_to_list(negdata_path)
print('positive instance',pos_list[0])
print('negative instance',neg_list[0])
len(pos_list), len(neg_list)

positive instance 质量好,做工也不错,尺码标准,
negative instance 穿上不舒服，颜色和质感跟图片差异很大，建议慎重购买！后悔了！


(1500, 1500)

In [5]:
from string import punctuation
punc = punctuation + u'.,;《》？！“”‘’@#￥%…&×（）——+【】{};；●，。&～、|\s:：'
punc

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~.,;《》？！“”‘’@#￥%…&×（）——+【】{};；●，。&～、|\\s:：'

In [6]:
import re
def rm_marks(str):
    str1 = re.sub(r"[{}]".format(punc),'',str)
    return str1

In [7]:
import random
# data_all = []
# label_all = []
pos_all = [[i,1] for i in pos_list]
neg_all = [[j,0] for j in neg_list]
data_all = pos_all + neg_all
random.shuffle(data_all)
data_all[:10]

[['质量是我想要的，男票穿着正好！下次有机会还来', 1],
 ['客服态度很好，裤子质量也不错，物流也快。很值的一次购物！！好评！！', 1],
 ['大小合适，质量不错，穿在身上效果很好', 1],
 ['挺差的，会起毛球', 0],
 ['穿上感觉挺舒服，这裤子质量还不错', 1],
 ['我实在想不通这样的裤子怎么达到98的好评率，特粘毛，还显脏。难道京东要像*台一样假货横行？人家越做越好，你呢', 0],
 ['你们发货没看码数的？', 0],
 ['差评给物流，看到已签收，不打电话还不知道签到哪里了，很不满意', 0],
 ['衣服穿在身上挺舒适的，满意的一次购物', 1],
 ['质量差，有色差，联系客服全是专业术语回复，无语，差差差差评', 0]]

In [8]:
data_X = [i[0] for i in data_all]
data_y = [i[1] for i in data_all]
data_X[:5], data_y[:5]

(['质量是我想要的，男票穿着正好！下次有机会还来',
  '客服态度很好，裤子质量也不错，物流也快。很值的一次购物！！好评！！',
  '大小合适，质量不错，穿在身上效果很好',
  '挺差的，会起毛球',
  '穿上感觉挺舒服，这裤子质量还不错'],
 [1, 1, 1, 0, 1])

In [65]:
'''本地的bert来做tokenize'''
from tqdm import tqdm
from transformers import BertTokenizer
bert_path = "../pretrained_model/chinese_roberta_wwm_ext_pytorch/"  # 该文件夹下存放三个文件（'vocab.txt', 'pytorch_model.bin', 'config.json'）
tokenizer = BertTokenizer.from_pretrained(bert_path,
                                          local_files_only=True)  # 初始化分词器
data_X1, input_masks, input_types, = [], [], []
labels = []  # 标签
maxlen = 40  # 取30即可覆盖99%

for i, line in tqdm(enumerate(data_X)):
    title = line
    encode_dict = tokenizer.encode_plus(text=title,
                                        max_length=maxlen,
                                        padding='max_length',
                                        truncation=True)
#     print(encode_dict['input_ids'])
    data_X1.append(encode_dict['input_ids'])

len(data_X1)

3000it [00:02, 1177.07it/s]


3000

In [10]:
len(data_y)

3000

In [11]:
# 利用train_test_split进行训练集和测试机进行分开，test_size占30%
X_train,X_test,y_train,y_test=train_test_split(data_X1,data_y,test_size=0.3)
print(X_train[0])

[101, 6821, 784, 720, 6175, 2094, 8024, 743, 1726, 3341, 6407, 6407, 8024, 2218, 3766, 4959, 6814, 8024, 3332, 3160, 2345, 4638, 679, 6121, 8024, 6820, 3766, 6125, 6804, 1765, 3033, 8114, 2571, 671, 816, 4638, 1962, 511, 102, 0]


In [12]:
len(X_train),len(X_test),len(y_train),len(y_test)

(2100, 900, 2100, 900)

## 数据预处理 - sklearn的trick

In [44]:
from sklearn import preprocessing

### 数据归一化

In [47]:
# 为了使得训练数据的标准化规则与测试数据的标准化规则同步，preprocessing中提供了很多Scaler：
data = [[0, 0], [0, 0], [1, 1], [1, 1]]
train_data = [[66, 213], [77, 0], [99, 1], [3252, 1]]
test_data = [[546, 1], [3251, 1], [15243, 1], [4325, 1]]
# 1. 基于mean和std的标准化
scaler = preprocessing.StandardScaler().fit(train_data)
scaler.transform(train_data)
scaler.transform(test_data)

# 2. 将每个特征值归一化到一个固定范围
scaler = preprocessing.MinMaxScaler(feature_range=(0, 1)).fit(train_data)
scaler.transform(train_data)
scaler.transform(test_data)
#feature_range: 定义归一化范围，注用（）括起来

array([[1.50659134e-01, 4.69483568e-03],
       [9.99686127e-01, 4.69483568e-03],
       [4.76365348e+00, 4.69483568e-03],
       [1.33678594e+00, 4.69483568e-03]])

### 正则化（normalize）

In [48]:
# 当你想要计算两个样本的相似度时必不可少的一个操作，就是正则化。其思想是：首先求出样本的p-范数，然后该样本的所有元素都要除以该范数，这样最终使得每个样本的范数都为1。
X = [[ 1., -1.,  2.],
     [ 2.,  0.,  0.],
     [ 0.,  1., -1.]]
X_normalized = preprocessing.normalize(X, norm='l2')
X_normalized                                      

array([[ 0.40824829, -0.40824829,  0.81649658],
       [ 1.        ,  0.        ,  0.        ],
       [ 0.        ,  0.70710678, -0.70710678]])

### one-hot编码

In [50]:
# one-hot编码是一种对离散特征值的编码方式，在LR模型中常用到，用于给线性模型增加非线性能力
data = [[0, 0, 3], [1, 1, 0], [0, 2, 1], [1, 0, 2]]
encoder = preprocessing.OneHotEncoder().fit(data)
encoder.transform(data).toarray()

array([[1., 0., 1., 0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 1., 0., 1., 0., 0.],
       [0., 1., 1., 0., 0., 0., 0., 1., 0.]])

### 数据集拆分

In [ ]:
# 　在得到训练数据集时，通常我们经常会把训练数据集进一步拆分成训练集和验证集，这样有助于我们模型参数的选取。
# 作用：将数据集划分为 训练集和测试集
# 格式：train_test_split(*arrays, **options)
from sklearn.model_selection import train_test_split
"""
参数
---
arrays：样本数组，包含特征向量和标签

test_size：
　　float-获得多大比重的测试样本 （默认：0.25）
　　int - 获得多少个测试样本

train_size: 同test_size

random_state:
　　int - 随机种子（种子固定，实验可复现）
　　
shuffle - 是否在分割之前对数据进行洗牌（默认True）

返回
---
分割后的列表，长度=2*len(arrays), 
　　(train-test split)
"""
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

## 模型的选择与训练

In [13]:
# MLP多层感知机（神经网络）的解法
from sklearn.neural_network import MLPClassifier
model = MLPClassifier(solver='adam',hidden_layer_sizes=(2000,2000),verbose=10, 
                      random_state=1,warm_start=True, early_stopping=True)
"""参数
---
    hidden_layer_sizes: 元祖
    activation：激活函数
    solver ：优化算法{‘lbfgs’, ‘sgd’, ‘adam’}
    alpha：L2惩罚(正则化项)参数。
"""
params = model.get_params()
params

{'activation': 'relu',
 'alpha': 0.0001,
 'batch_size': 'auto',
 'beta_1': 0.9,
 'beta_2': 0.999,
 'early_stopping': True,
 'epsilon': 1e-08,
 'hidden_layer_sizes': (2000, 2000),
 'learning_rate': 'constant',
 'learning_rate_init': 0.001,
 'max_fun': 15000,
 'max_iter': 200,
 'momentum': 0.9,
 'n_iter_no_change': 10,
 'nesterovs_momentum': True,
 'power_t': 0.5,
 'random_state': 1,
 'shuffle': True,
 'solver': 'adam',
 'tol': 0.0001,
 'validation_fraction': 0.1,
 'verbose': 10,
 'warm_start': True}

In [18]:
# 线性回归
from sklearn.linear_model import LinearRegression
# 定义线性回归模型
model = LinearRegression(fit_intercept=True, normalize=False, 
    copy_X=True, n_jobs=1)
"""
参数
---
    fit_intercept：是否计算截距。False-模型没有截距
    normalize： 当fit_intercept设置为False时，该参数将被忽略。 如果为真，则回归前的回归系数X将通过减去平均值并除以l2-范数而归一化。
     n_jobs：指定线程数
"""
params = model.get_params()
params

{'copy_X': True, 'fit_intercept': True, 'n_jobs': None, 'normalize': True}

In [42]:
#  逻辑回归LR
from sklearn.linear_model import LogisticRegression
# 定义逻辑回归模型
"""参数
---
    penalty：使用指定正则化项（默认：l2）
    dual: n_samples > n_features取False（默认）
    C：正则化强度的反，值越小正则化强度越大
    n_jobs: 指定线程数
    random_state：随机数生成器
    fit_intercept: 是否需要常量
"""
model = LogisticRegression(penalty='l2', dual=False, tol=0.0001, C=1.0, 
    fit_intercept=True, intercept_scaling=1, class_weight=None, 
    random_state=None, solver='liblinear', max_iter=100, multi_class='ovr', 
    verbose=0, warm_start=False, n_jobs=1)
params = model.get_params()
params

In [68]:
# 支持向量机SVM
from sklearn.svm import SVC
model = SVC(C=1.0, kernel='rbf', gamma='auto')
"""参数
---
    C：误差项的惩罚参数C
    gamma: 核相关系数。浮点数，If gamma is ‘auto’ then 1/n_features will be used instead.
"""
params = model.get_params()
params

{'C': 1.0,
 'break_ties': False,
 'cache_size': 200,
 'class_weight': None,
 'coef0': 0.0,
 'decision_function_shape': 'ovr',
 'degree': 3,
 'gamma': 'auto',
 'kernel': 'rbf',
 'max_iter': -1,
 'probability': False,
 'random_state': None,
 'shrinking': True,
 'tol': 0.001,
 'verbose': False}

In [71]:
a = 1
bool(a)

True

In [38]:
#  朴素贝叶斯算法NB
from sklearn import naive_bayes
"""
文本分类问题常用MultinomialNB
参数
---
    alpha：平滑参数
    fit_prior：是否要学习类的先验概率；false-使用统一的先验概率
    class_prior: 是否指定类的先验概率；若指定则不能根据参数调整
    binarize: 二值化的阈值，若为None，则假设输入由二进制向量组成
"""
model = naive_bayes.GaussianNB() # 高斯贝叶斯
# model = naive_bayes.MultinomialNB(alpha=1.0, fit_prior=True, class_prior=None)
# model = naive_bayes.BernoulliNB(alpha=1.0, binarize=0.0, fit_prior=True, class_prior=None)
params = model.get_params()
params

In [ ]:
# 决策树DT
from  sklearn  import  tree 
"""参数
---
    criterion ：特征选择准则gini/entropy
    max_depth：树的最大深度，None-尽量下分
    min_samples_split：分裂内部节点，所需要的最小样本树
    min_samples_leaf：叶子节点所需要的最小样本数
    max_features: 寻找最优分割点时的最大特征数
    max_leaf_nodes：优先增长到最大叶子节点数
    min_impurity_decrease：如果这种分离导致杂质的减少大于或等于这个值，则节点将被拆分。
"""
model = tree.DecisionTreeClassifier(criterion=’gini’, max_depth=None, 
    min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, 
    max_features=None, random_state=None, max_leaf_nodes=None, 
    min_impurity_decrease=0.0, min_impurity_split=None,
     class_weight=None, presort=False)
params = model.get_params()
params

In [36]:
# knn
from sklearn import neighbors
#定义kNN分类模型
model = neighbors.KNeighborsClassifier(n_neighbors=5, n_jobs=1) # 分类
# model = neighbors.KNeighborsRegressor(n_neighbors=5, n_jobs=1) # 回归
"""参数
---
    n_neighbors： 使用邻居的数目
    n_jobs：并行任务数
"""
params = model.get_params()
params

In [34]:
# PCA
from sklearn.decomposition import PCA
model = PCA(n_components=0.95)
params = model.get_params()
params

In [25]:
# k-means
from sklearn.cluster import KMeans
model = KMeans(n_clusters=10, random_state=0)
params = model.get_params()
params

In [70]:
help(KMeans)

Help on class KMeans in module sklearn.cluster._kmeans:

class KMeans(sklearn.base.TransformerMixin, sklearn.base.ClusterMixin, sklearn.base.BaseEstimator)
 |  KMeans(n_clusters=8, *, init='k-means++', n_init=10, max_iter=300, tol=0.0001, precompute_distances='deprecated', verbose=0, random_state=None, copy_x=True, n_jobs='deprecated', algorithm='auto')
 |  
 |  K-Means clustering.
 |  
 |  Read more in the :ref:`User Guide <k_means>`.
 |  
 |  Parameters
 |  ----------
 |  
 |  n_clusters : int, default=8
 |      The number of clusters to form as well as the number of
 |      centroids to generate.
 |  
 |  init : {'k-means++', 'random', ndarray, callable}, default='k-means++'
 |      Method for initialization:
 |  
 |      'k-means++' : selects initial cluster centers for k-mean
 |      clustering in a smart way to speed up convergence. See section
 |      Notes in k_init for more details.
 |  
 |      'random': choose `n_clusters` observations (rows) at random from data
 |      for 

In [43]:
model.fit(X_train,y_train)
score = model.score(X_test,y_test)
print("预测得分为：%s"%score)

预测得分为：0.7011111111111111


In [16]:
sen = "质量不错，尺码大小合适，很喜欢"
aa = tokenizer.encode_plus(text=sen, max_length=maxlen, padding='max_length', truncation=True)
token_sen = [aa["input_ids"]]
print(model.predict(token_sen))

[1]


In [17]:
sen = "太好了，很棒啊，太厉害了"
aa = tokenizer.encode_plus(text=sen, max_length=maxlen, padding='max_length', truncation=True)
token_sen = [aa["input_ids"]]
print(model.predict(token_sen))

[0]


## 模型评估与选择篇

### 交叉验证

In [57]:
from sklearn.model_selection import cross_val_score
"""参数
---
    model：拟合数据的模型
    cv ： k-fold
    scoring: 打分参数-‘accuracy’、‘f1’、‘precision’、‘recall’ 、‘roc_auc’、'neg_log_loss'等等
"""
cross_val_score(model, X_test, y_test, scoring=None, cv=None, n_jobs=1)

array([0.71111111, 0.65555556, 0.65      , 0.78333333, 0.69444444])

### 检验曲线

In [ ]:
# 使用检验曲线，我们可以更加方便的改变模型参数，获取模型表现。
from sklearn.model_selection import validation_curve
"""参数
---
    model:用于fit和predict的对象
    X, y: 训练集的特征和标签
    param_name：将被改变的参数的名字
    param_range： 参数的改变范围
    cv：k-fold
   
返回值
---
   train_score: 训练集得分（array）
    test_score: 验证集得分（array）
"""
train_score, test_score = validation_curve(model, X_test, y_test, params, param_range=(1,100), cv=None, scoring=None, n_jobs=1)

## 保存模型

最后，我们可以将我们训练好的model保存到本地，或者放到线上供用户使用，那么如何保存训练好的model呢？主要有下面两种方式：

In [ ]:
# 保存为pickle文件
import pickle

# 保存模型
with open('model.pickle', 'wb') as f:
    pickle.dump(model, f)

# 读取模型
with open('model.pickle', 'rb') as f:
    model = pickle.load(f)
model.predict(X_test)

In [ ]:
# sklearn自带方法joblib
from sklearn.externals import joblib

# 保存模型
joblib.dump(model, 'model.pickle')

#载入模型
model = joblib.load('model.pickle')