# dataset与dataloader

In [1]:
import torch as t
from torch.utils.data import DataLoader, Dataset

In [2]:
class stupidDataset(Dataset):
    def __init__(self):
        super(stupidDataset, self).__init__()
        self.data = t.randn([1024, 10, 10])
    def __len__(self):
        return 1024
    def __getitem__(self, idx):
        return self.data[idx, :, :]

In [3]:
myDataset = stupidDataset()
myDataset.__getitem__(4)

tensor([[-8.0703e-01,  1.0081e+00,  4.9871e-01,  4.2091e-01, -8.2539e-01,
          9.4630e-01, -8.4458e-01, -4.5446e-01, -8.4125e-01,  1.6540e-03],
        [ 5.6305e-01,  6.1709e-03, -1.8391e+00,  1.5555e+00, -1.7109e+00,
          1.5124e+00,  7.2579e-02,  1.9280e-01,  3.0775e-01, -3.3496e-01],
        [ 2.2136e+00,  8.8353e-01,  1.9561e+00, -1.5309e+00, -7.8106e-01,
         -1.3031e-01, -9.8051e-01, -3.8523e-01, -7.9776e-01, -1.4329e+00],
        [-2.4452e-01, -5.1423e-01,  1.1383e+00, -1.5971e-01,  9.7312e-01,
          3.2846e-01, -1.1180e+00,  8.5156e-01,  1.4350e+00,  9.7195e-01],
        [-6.7695e-02, -2.2367e+00,  3.5707e-01,  6.1028e-01, -1.1150e+00,
          7.5514e-02, -1.7065e-01,  4.0903e-02,  7.5758e-01,  3.0094e-01],
        [-1.0697e+00, -9.0452e-01, -2.4910e+00,  8.8355e-01, -1.5530e-01,
          3.5701e-01, -8.1018e-01, -1.8017e-01, -1.3180e+00,  1.3886e-01],
        [ 2.2317e-01,  7.4580e-01,  5.9833e-01,  1.0631e+00,  6.2529e-01,
         -9.5183e-01, -5.0630e-0

In [4]:
myDataLoader = DataLoader(myDataset, batch_size=8, shuffle=True)

In [5]:
for batch in myDataLoader:
    print(type(batch))
    print(batch)
    break

<class 'torch.Tensor'>
tensor([[[-2.1178e-01,  1.0011e-01, -1.0115e+00,  1.1360e+00, -1.8632e-02,
           1.7381e+00,  1.2756e+00,  8.4940e-01, -9.6178e-01, -9.5738e-01],
         [-6.9404e-01,  8.7622e-01,  5.2550e-01,  2.8259e-01,  1.0582e+00,
           1.2162e+00,  9.9070e-01, -1.2307e+00,  7.7286e-01, -3.8089e-01],
         [-1.4156e+00, -1.5317e+00,  8.0024e-01, -1.0498e+00, -1.5230e+00,
          -6.6290e-01, -1.6435e+00, -1.4025e-01, -5.5473e-01, -2.2014e+00],
         [-3.4537e-01,  1.2075e+00, -1.2469e+00,  1.8984e+00, -2.8378e-01,
           8.3003e-01,  1.2355e+00, -8.5010e-01,  9.1295e-01,  1.7441e+00],
         [ 1.3839e-02,  1.2052e+00, -2.1211e-01, -6.8069e-01,  4.8237e-01,
          -1.7739e+00,  1.1605e+00, -5.8525e-02, -2.7748e-01, -8.1477e-01],
         [-1.8015e-01,  6.0451e-01,  1.1620e-01,  4.7831e-01, -5.0678e-02,
           1.0913e-01, -8.1077e-01, -1.8000e+00,  1.1261e+00,  1.3804e-01],
         [ 8.5902e-01,  4.8657e-01, -4.3958e-01,  1.3543e+00,  1.3136e+

In [6]:
class myDictDataset(Dataset):
    def __init__(self):
        super(myDictDataset, self).__init__()
        self.x = t.randn(1024, 10)
        self.y = t.randn(1024)
    def __len__(self):
        return 1024
    def __getitem__(self, idx):
        return {'x':self.x[idx,:], 'y':self.y[idx]}

In [7]:
dict_dataset = myDictDataset()
dict_data_loader = DataLoader(dict_dataset, batch_size=8, shuffle=True)

In [8]:
for batch in dict_data_loader:
    print(type(batch))
    print(batch)
    break

<class 'dict'>
{'x': tensor([[ 3.9640e-01,  4.1741e-01,  1.4149e+00,  1.2494e+00,  4.4478e-01,
          3.4844e-01, -1.6358e+00,  6.3027e-01,  2.0127e-01, -1.6155e+00],
        [-4.8166e-01,  9.1485e-01, -1.4071e+00, -5.3531e-01,  2.3638e+00,
          5.2530e-01, -1.7273e+00,  1.6220e+00, -7.2781e-01,  2.0504e-01],
        [-9.3257e-01,  1.1848e-01, -5.8681e-02,  4.2096e-02, -2.3757e-01,
          1.8675e+00,  9.6308e-01, -9.9944e-01,  3.9960e-01, -1.2797e+00],
        [ 2.0033e+00,  3.6807e-01, -1.2842e+00, -9.4076e-01, -1.4578e+00,
         -9.6587e-01,  2.4746e-01,  5.0514e-01, -1.6296e+00, -9.5701e-01],
        [ 1.0384e+00, -8.1384e-01, -9.6765e-01,  3.0825e-01,  8.6444e-01,
          1.6183e+00, -1.4120e+00,  1.0104e+00,  1.4594e+00, -7.2649e-01],
        [-9.7242e-01,  1.7257e-03,  9.9869e-01,  9.8795e-01, -4.9672e-01,
         -1.5989e+00,  8.3445e-01,  8.9663e-01,  7.3790e-01,  7.6431e-01],
        [ 1.0440e-01, -1.7642e+00,  6.5688e-01, -1.2589e-03,  8.1045e-01,
         -9

In [9]:
from torch.utils.data import TensorDataset # specific dataset class
x = t.randn(10, 100)
y = t.randn(10)
tensor_dataset = TensorDataset(x, y)

# model

构建网络的时候最麻烦的就是dimension

In [10]:
import torch
import torch.nn as nn
x = torch.rand([8, 100, 10]).detach()
y = torch.rand(8)
y = (y>0.5).int() # 变成分类问题

In [11]:
class MLP(nn.Module):
    def __init__(self):
        super(MLP, self).__init__()
        self.first_layer = nn.Linear(1000, 50)
        self.second_layer = nn.Linear(50, 1)
    def forward(self, x):
        x = torch.flatten(x, start_dim = 1, end_dim = 2)
        x = nn.functional.relu(self.first_layer(x))
        x = self.second_layer(x)
        return x

In [12]:
mlp = MLP()
output = mlp(x)
output

tensor([[-0.2913],
        [-0.2884],
        [-0.2988],
        [-0.3141],
        [-0.2575],
        [-0.1869],
        [-0.2789],
        [-0.3035]], grad_fn=<AddmmBackward>)

In [13]:
class Embedding(nn.Module):
    def __init__(self):
        super(Embedding, self).__init__()
        self.embedding = nn.Embedding(4, 100)
    def forward(self, x):
        return self.embedding(x)

In [14]:
embedding = Embedding()
embedding_input = t.tensor([[0, 1, 0],[2, 3, 3]])
embedding_output = embedding(embedding_input)

In [17]:
embedding_output.shape

torch.Size([2, 3, 100])

In [18]:
class LSTM(nn.Module):
    def __init__(self):
        super(LSTM, self).__init__()
        self.lstm = nn.LSTM(10, 15, num_layers = 2, bidirectional=True, dropout=0.1)
    def forward(self, x):
        output, (hidden, cell) = self.lstm(x)
        return output, hidden, cell

In [20]:
permute_x = x.permute([1, 0, 2])
lstm = LSTM()
output_lstm1, output_lstm2, output_lstm3 = lstm(permute_x)
output_lstm1.shape, output_lstm2.shape, output_lstm3.shape

(torch.Size([100, 8, 30]), torch.Size([4, 8, 15]), torch.Size([4, 8, 15]))

In [21]:
class Conv(nn.Module):
    def __init__(self):
        super(Conv, self).__init__()
        self.conv1d = nn.Conv1d(100, 50, 2)
    def forward(self, x):
        return self.conv1d(x)

In [22]:
conv = Conv()
output = conv(x)
output.shape

torch.Size([8, 50, 9])

# 文本分类

In [23]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\小钒\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [24]:
from nltk.tokenize import word_tokenize
tokenizer = word_tokenize

In [28]:
import torch
from torchtext import data
from torchtext import datasets

SEED = 1234

torch.manual_seed(SEED)
torch.backends.cudnn.deterministicc = True

TEXT = data.Field(tokenize = tokenizer, include_lengths = True)
LABEL = data.LabelField(dtype = torch.float)

AttributeError: module 'torchtext.data' has no attribute 'Field'

In [ ]:
from torchtext import datasets
train_data, test_data = datasets.IMDB.splits(TEXT, LABEL) # 除了下载分词也做了，所以比较慢
import random
train_data, valid_data = train_data.split(random_state= random.seed(SEED))
MAX_VOCAB_SIZE = 25000

TEXT.build_vocab(train_data, max_size = MAX_VOCAB_SIZE, vectors = "glove.6B.300d", unk_init = torch.Tensor.normal_) # google wordvec 6word guess
LABEL.build_vocab(train_data)
BATCH_SIZE = 8
# device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device = torch.device('cpu')
device

In [ ]:
# dataloader
train_iterator, valid_iterator, test_iterator = data.BucketIterator.splits((train_data, valid_data, test_data), batch_size=BATCH_SIZE,
                                                                            sort_within_batch=True,device = device)

In [ ]:
import torch.nn as nn

class RNN(nn.Module):
    def __init__(self, vocab_size, embedding_dim, hidden_dim, output_dim, n_layers, 
                 bidirectional, dropout, pad_idx):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, embedding_dim, padding_idx = pad_idx)
        self.rnn = nn.LSTM(embedding_dim, 
                           hidden_dim, 
                           num_layers=n_layers, 
                           bidirectional=bidirectional, 
                           dropout=dropout)
        self.fc = nn.Linear(hidden_dim * 2, output_dim)
        self.dropout = nn.Dropout(dropout)
    def forward(self, text, text_lengths):
        embedded = self.embedding(text)
        text_lengths = torch.tensor(list(text_lengths)).int()
        packed_embedded = nn.utils.rnn.pack_padded_sequence(embedded, text_lengths)
        packed_output, (hidden, cell) = self.rnn(packed_embedded)
        output, output_lengths = nn.utils.rnn.pad_packed_sequence(packed_output)
        hidden = self.dropout(torch.cat((hidden[-2,:,:], hidden[-1,:,:]), dim = 1))    
        return self.fc(hidden)

In [ ]:
INPUT_DIM = len(TEXT.vocab)
EMBEDDING_DIM = 300
HIDDEN_DIM = 256
OUTPUT_DIM = 1
N_LAYERS = 2
BIDIRECTIONAL = True
DROPOUT = 0.2
PAD_IDX = TEXT.vocab.stoi[TEXT.pad_token]
model = RNN(INPUT_DIM,EMBEDDING_DIM,HIDDEN_DIM,OUTPUT_DIM,N_LAYERS,BIDIRECTIONAL,DROPOUT,PAD_IDX)

In [ ]:
pretrained_embeddings = TEXT.vocab.vectors
model.embedding.weight.data.copy_(pretrained_embeddings) # 把embedding给model

In [ ]:
UNK_IDX = TEXT.vocab.stoi[TEXT.unk_token]
model.embedding.weight.data[UNK_IDX] = torch.zeros(EMBEDDING_DIM)
model.embedding.weight.data[PAD_IDX] = torch.zeros(EMBEDDING_DIM)

In [ ]:
import torch.optim as optim

optimizer = optim.Adam(model.parameters())
criterion = nn.BCEWithLogitsLoss()

model = model.to(device)
criterion = criterion.to(device)

In [ ]:
def binary_accuracy(preds, y):
    """
    Returns accuracy per batch, i.e. if you get 8/10 right, this returns 0.8, NOT 8
    """

    #round predictions to the closest integer
    rounded_preds = torch.round(torch.sigmoid(preds))
    correct = (rounded_preds == y).float() #convert into float for division 
    acc = correct.sum() / len(correct)
    return acc

In [ ]:
def train(model, iterator, optimizer, criterion):
    epoch_loss = 0
    epoch_acc = 0
    model.train()
    length_when = 0
    for batch in iterator:
        optimizer.zero_grad()
        text, text_lengths = batch.text
        predictions = model(text, text_lengths).squeeze(1)
        loss = criterion(predictions, batch.label)
        acc = binary_accuracy(predictions, batch.label)
        # print(f'predictions : {predictions},loss: {loss}, acc : {acc}')
        loss.backward()
        optimizer.step()
        epoch_loss += loss.item()
        epoch_acc += acc.item()
        length_when += 1
        print(f'epoch loss: {epoch_loss / length_when}, epoch_acc : {epoch_acc / length_when}')
    return epoch_loss / len(iterator), epoch_acc / len(iterator)

In [ ]:
def evaluate(model, iterator, criterion):
    epoch_loss = 0
    epoch_acc = 0
    model.eval()
    length_when = 0
    with torch.no_grad():
        for batch in iterator:
            text, text_lengths = batch.text
            predictions = model(text, text_lengths).squeeze(1)
            loss = criterion(predictions, batch.label)
            acc = binary_accuracy(predictions, batch.label)
            # print(f'predictions : {predictions},loss: {loss}, acc : {acc}')
            epoch_loss += loss.item()
            epoch_acc += acc.item()
            length_when += 1
            print(f'epoch loss: {epoch_loss / length_when}, epoch_acc : {epoch_acc / length_when}')
    return epoch_loss / len(iterator), epoch_acc / len(iterator)

In [ ]:
import time
def epoch_time(start_time, end_time):
    elapsed_time = end_time - start_time
    elapsed_mins = int(elapsed_time / 60)
    elapsed_secs = int(elapsed_time - (elapsed_mins * 60))
    return elapsed_mins, elapsed_secs

In [ ]:
N_EPOCHS = 2
best_valid_loss = float('inf')
for epoch in range(N_EPOCHS):
    start_time = time.time()
    train_loss, train_acc = train(model, train_iterator, optimizer, criterion)
    valid_loss, valid_acc = evaluate(model, valid_iterator, criterion)
    end_time = time.time()

    epoch_mins, epoch_secs = epoch_time(start_time, end_time)
    
    if valid_loss < best_valid_loss:
        best_valid_loss = valid_loss
        torch.save(model.state_dict(), 'model.pt')
    
    print(f'Epoch: {epoch+1:02} | Epoch Time: {epoch_mins}m {epoch_secs}s')
    print(f'\tTrain Loss: {train_loss:.3f} | Train Acc: {train_acc*100:.2f}%')
    print(f'\t Val. Loss: {valid_loss:.3f} |  Val. Acc: {valid_acc*100:.2f}%')

In [ ]:
model.load_state_dict(torch.load('model.pt'))

test_loss, test_acc = evaluate(model, test_iterator, criterion)

print(f'Test Loss: {test_loss:.3f} | Test Acc: {test_acc*100:.2f}%')

# Structured Data Mining

In [ ]:
! wget https://www.stats.govt.nz/assets/Uploads/New-Zealand-business-demography-statistics/New-Zealand-business-demography-statistics-At-February-2019/Download-data/geographic-units-by-industry-and-statistical-area-2000-19-descending-order.zip

In [ ]:
import pandas as pd
in_file = "./geographic_data/Data7602DescendingYearOrder.csv"
data = pd.read_csv(in_file, engine='python')
data.head()

In [ ]:
data.columns.values
# data.to_csv("out_file.csv", index = False, encoding='utf-8', sep='\t') #写入csv